### ISSUE TITLE
Please add Oman prayer calculation method

### ISSUE THREAD

**Issue by Alshukaily** [uchagani/prayer-times-calculator#14]
hello brothers @uchagani @fabaff @engrbm87 
Could you please consider adding Oman in the calculation method in this integration?

**Comment by uchagani** [comment]
Oman is not a valid type for the API.  These are just calculation methods so unless Oman has a different calculation method I think you should be safe using one of the other ones.  Or if you know the details of the Oman calculation methods you can use the Custom calculation method and enter the details.

Calculation methods supported by the API:

![image](https://user-images.githubusercontent.com/1053584/133474339-1a6598d5-453a-4c91-aec5-5c770425b00c.png)

**Comment by Alshukaily** [comment]
There is actually a calculation method for Oman I saw it in one of the android app called SALATUK and it was completely accurate. I tried MWL in your integration it was close just a few minutes between some prayers and more than 10 for others. I don't know from where to get these calculation methods so I can use it in custom option. even if I get it I don't know how to do it. I will try to ask the ministry here in Oman.

**Comment by engrbm87** [comment]
Once PR #51293 is merged you will have the option to tune the prayer times to be more accurate. I am just waiting for the PR to be reviewed. In the meantime you can test it out as a custom component from [this link](https://github.com/engrbm87/HA-islamic-prayer-times).

**Comment by uchagani** [comment]
@Alshukaily This particular library is only a wrapper around https://aladhan.com/prayer-times-api and that doesn't seem to have an option for Oman.  As @engrbm87 said, if using Home Assistant, you should soon be able to tune the timings.  

I have two suggestions:

1. contact SALATUK and see what calculations they use then use the custom option.
2. contact https://aladhan.com/contact and see if they will add an option for Oman.  They seem to have a discord server where you might be able to get a quicker response.

**Comment by Alshukaily** [comment]
@uchagani  1. I already contacted them and I am waiting for their answer.
2. I will try to contact them, it is just difficult they required a Developer Mailing List subscription and I am waiting for the confirmation e-mail for the second day.
@engrbm87 Thank you for this it will help me for now until I get Oman timing added to the API, but then I will need little research on how to test the PR.

**Comment by uchagani** [comment]
@Alshukaily don’t Fill out the form on their site, if you look above the form you will see an email address. Email them on that. Also they have a discord server you can join.

**Comment by Alshukaily** [comment]
@uchagani Yes I found it I joined the discord, and I will try to email them as well. Thanks

**Comment by uchagani** [comment]
Please reopen if the API adds Oman.
