### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by yasn77** [uchagani/prayer-times-calculator#18]
HI @uchagani 

Would it be possible to cut a new release (after #17 has been merged)?

I would like to make use of the PR's I have submitted in Home Assistant (yep, after I update the plugin code 😄 )

**Comment by yasn77** [comment]
@uchagani Any chance you tag a new release?

Thanks

**Comment by uchagani** [comment]
I'll definitely try to get one out this weekend.

**Comment by uchagani** [comment]
[v0.0.6](https://pypi.org/project/prayer-times-calculator/0.0.6/) has been released
