### ISSUE TITLE
Add additional paramters to times calculation

### ISSUE THREAD

**Issue by engrbm87** [uchagani/prayer-times-calculator#3]
I have seen that there is a PR to add new calculation methods. I would like to also add the other parameters available in the api request including:
- school: 0 for Shafi, 1 for Hanafi
- midnight mode
- latitudeAdjustmentMethod

Also it would be great to include a method that returns the 'date' key from the response which can be used for example in Home assistant to display the 'Hijri' date. 
I can work on a PR if you are interested in updating the code.

**Comment by uchagani** [comment]
Yes definitely interested. Thanks. I'll take a look at the other open PR.
If I remember there needed to be updates to it but the person never made
them. If you'd like to incorporate those changes into your PR that would be
great too.
