### ISSUE TITLE
Release version 0.4 to pyPi for integration?

### ISSUE THREAD

**Issue by sbou88** [uchagani/prayer-times-calculator#5]
Salam a3laykoum, 

All is on title, can you release this version with new calculating method ?

Thx in advance

**Comment by uchagani** [comment]
Wa ‘alaykum as-salaam sorry about that. I'll get a new release out this week in sha Allah.

**Comment by uchagani** [comment]
sorry for the delay.  there is another PR open right now, as soon as that is merged i'll push a new release.

**Comment by uchagani** [comment]
@sbou88 0.0.4 has been released.
